### ISSUE TITLE
the special case of returning NaN for inverse problem

### ISSUE THREAD

**Issue by kkdd** [geographiclib/geographiclib-js#3]
Hello,
I realized that geodesic.Geodesic.WGS84.Inverse(45, 0, -45, 179.572719) returns {"lat1": 45, "lat2": -45, "lon1": 0, "lon2": 179.572719, "a12": NaN, "s12": NaN, "azi1": 90, "azi2": NaN}, using geographiclib-geodesic.js (Version: 2.0.0).

**Comment by cffk** [comment]
Thanks for this report.  I'll investigate.  I believe it's a corner case peculiar to lats = +/-45.

**Comment by cffk** [comment]
This is fixed now on the devel branch.  I'll make a new release within a month.

**Comment by kkdd** [comment]
Thank you your quick fix. I confirmed that it fixed this problem.

**Comment by cffk** [comment]
Version 2.1.1 includes this fix.
