### ISSUE TITLE
Sourceforge link to geographiclib.js

### ISSUE THREAD

**Issue by AlexanderAdelAU** [geographiclib/geographiclib-js#4]
I suspect that the removal of 
[<script src="https://geographiclib.sourceforge.io/scripts/geographiclib.min.js"></script>]
may have broken a few sites.   Fortunately I have a copy of the source and can host it locally on the server, but the issues is why split and cause users the problem of figuring out how to use the separated packages, and which ones to use.

Surely there is nothing lost, by making a combined version available.

**Comment by cffk** [comment]
OK, I've restored these files (links actually).

**Comment by AlexanderAdelAU** [comment]
> OK, I've restored these files (links actually).

Great, thankyou.
